spring.config.import=optional:classpath:env.properties

server.port=6969
jwt.secret=${JWT_SECRET}

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

supabase.url=${SUPABASE_URL:https://your-project-ref.supabase.co}/
supabase.service-key=${SUPABASE_SERVICE_KEY:your-service-key}

logging.level.org.springframework=TRACE