TAG_MAPPING = {
    "beef": "MEAT",
    "steak": "MEAT",
    "burger": "MEAT",
    "pork": "MEAT",
    "ham": "MEAT",
    "bacon": "MEAT",
    "sausage": "MEAT",
    "chicken": "MEAT",
    "turkey": "MEAT",
    "duck": "MEAT",
    "lamb": "MEAT",
    "meat": "MEAT",

    "fish": "FISH",
    "salmon": "FISH",
    "tuna": "FISH",
    "cod": "FISH",
    "trout": "FISH",
    "sardine": "FISH",
    "anchovy": "FISH",
    "mackerel": "FISH",

    "shrimp": "SEAFOOD",
    "prawn": "SEAFOOD",
    "crab": "SEAFOOD",
    "lobster": "SEAFOOD",
    "mussels": "SEAFOOD",
    "octopus": "SEAFOOD",
    "calamari": "SEAFOOD",
    "squid": "SEAFOOD",
    "seafood": "SEAFOOD",

    "egg": "EGGS",
    "eggs": "EGGS",
    "cheese": "CHEESE",
    "potato": "POTATO",
    "onion": "ONION",
    "garlic": "GARLIC",
    "bread": "BREAD",
    "salad": "SALAD",
    "rice": "RICE",
    "noodles": "NOODLES",
    "lentils": "LENTILS",
    "beans": "BEANS",
    "soup": "SOUP"
}